"""Enumerate the real ``prototype-type`` value set and the true English page count.

Run once in Phase 0 to complete ``type_map`` from what the wiki actually contains.
Caches the fetched infobox wikitext to ``data/cache/`` so re-analysis costs no requests.

    .venv/bin/python scripts/enumerate_types.py           # fetch, then analyse
    .venv/bin/python scripts/enumerate_types.py --cached   # analyse the cache only
"""

from __future__ import annotations

import json
import re
import sys
from collections import Counter
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))

from ragtorio.config import Settings, load_profile
from ragtorio.harvest.client import MediaWikiClient
from ragtorio.harvest.probe import LANGUAGE_SUFFIX

PROTOTYPE_TYPE = re.compile(r"\|\s*prototype-type\s*=\s*([^\n|}]+)")
BATCH = 50
CACHE = Path("data/cache/factorio_phase0.json")

#: prototype-type values that are not plain items. Everything else maps to [Item];
#: the :Station label is added at graph-load time to whatever receives CRAFTED_AT
#: edges, so we never hand-maintain a list of which machines craft.
SPECIAL_LABELS: dict[str, list[str]] = {
    "technology": ["Unlock"],
    "recipe": ["Recipe"],
    "fluid": ["Item", "Fluid"],
    "character": ["Station"],
}


def titles_in(client: MediaWikiClient, namespace: int) -> list[str]:
    return [
        str(page["title"])
        for chunk in client.query_paged(
            list="allpages", apnamespace=namespace, aplimit=500, apfilterredir="nonredirects"
        )
        for page in chunk.get("allpages", [])
    ]


def fetch() -> dict[str, object]:
    profile = load_profile("factorio")
    settings = Settings()
    infobox_ns = profile.infobox.namespace_id
    assert infobox_ns is not None

    with MediaWikiClient(
        profile.wiki.api, settings.user_agent, rps=profile.wiki.rate_limit_rps
    ) as client:
        print("enumerating mainspace...", flush=True)
        mainspace = titles_in(client, 0)
        print(f"enumerating namespace {infobox_ns}...", flush=True)
        infobox_titles = titles_in(client, infobox_ns)
        english_infobox = [t for t in infobox_titles if not LANGUAGE_SUFFIX.search(t)]

        print(f"fetching {len(english_infobox)} infobox pages...", flush=True)
        wikitext: dict[str, str] = {}
        for i in range(0, len(english_infobox), BATCH):
            batch = english_infobox[i : i + BATCH]
            data = client.query(
                prop="revisions", rvprop="content", rvslots="main", titles="|".join(batch)
            )
            for page in data.get("pages", []):
                revisions = page.get("revisions") or []
                if revisions:
                    wikitext[str(page["title"])] = revisions[0]["slots"]["main"].get("content", "")
            print(f"  {min(i + BATCH, len(english_infobox))}/{len(english_infobox)}", flush=True)

    payload = {
        "mainspace_titles": mainspace,
        "infobox_titles": infobox_titles,
        "infobox_wikitext": wikitext,
    }
    CACHE.parent.mkdir(parents=True, exist_ok=True)
    CACHE.write_text(json.dumps(payload), encoding="utf-8")
    print(f"cached to {CACHE}")
    return payload


def analyse(payload: dict[str, object]) -> None:
    mainspace: list[str] = payload["mainspace_titles"]  # type: ignore[assignment]
    infobox_titles: list[str] = payload["infobox_titles"]  # type: ignore[assignment]
    wikitext: dict[str, str] = payload["infobox_wikitext"]  # type: ignore[assignment]

    english = [t for t in mainspace if not LANGUAGE_SUFFIX.search(t)]
    english_infobox = [t for t in infobox_titles if not LANGUAGE_SUFFIX.search(t)]

    types: Counter[str] = Counter()
    untyped: list[str] = []
    for title, text in wikitext.items():
        match = PROTOTYPE_TYPE.search(text)
        if match:
            types[match.group(1).strip()] += 1
        else:
            untyped.append(title)

    # What do untyped infobox pages use instead? Look at their first template name.
    untyped_templates: Counter[str] = Counter()
    for title in untyped:
        found = re.search(r"\{\{\s*([A-Za-z][\w :-]*)", wikitext[title])
        untyped_templates[found.group(1).strip() if found else "(none)"] += 1

    lines = [
        "# Factorio Phase 0: measured page counts and prototype-type value set",
        "",
        "Generated by `scripts/enumerate_types.py`. Numbers are from the live wiki.",
        "",
        "## Page counts",
        "",
        "| set | count |",
        "|---|---|",
        f"| mainspace, all languages | {len(mainspace):,} |",
        f"| mainspace, English | **{len(english):,}** |",
        f"| Infobox: namespace, all languages | {len(infobox_titles):,} |",
        f"| Infobox: namespace, English | **{len(english_infobox):,}** |",
        f"| infobox pages carrying prototype-type | {len(wikitext) - len(untyped):,} |",
        f"| infobox pages without prototype-type | {len(untyped):,} |",
        "",
        f"The Infobox: namespace is not translated ({len(infobox_titles)} pages, "
        f"{len(english_infobox)} English), so no language filter is needed there.",
        f"Roughly half of English articles ({len(english_infobox)} of {len(english)}) have an "
        "infobox; the rest are mechanics prose, which is what the vector index is for.",
        "",
        "## Infobox pages without prototype-type",
        "",
        "| leading template | pages |",
        "|---|---|",
        *(f"| `{name}` | {count} |" for name, count in untyped_templates.most_common()),
        "",
        f"Titles: {', '.join(f'`{t}`' for t in sorted(untyped)[:40])}",
        "",
        "## prototype-type values, by frequency",
        "",
        "| value | pages | labels |",
        "|---|---|---|",
        *(
            f"| `{value}` | {count} | {SPECIAL_LABELS.get(value, ['Item'])} |"
            for value, count in types.most_common()
        ),
    ]
    out = Path("docs/coverage/phase0-type-enumeration.md")
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(lines) + "\n", encoding="utf-8")

    yaml_lines = [
        f"    {value}: {json.dumps(SPECIAL_LABELS.get(value, ['Item']))}"
        for value, _ in types.most_common()
    ]
    Path("data/cache/type_map_block.yaml").write_text(
        "\n".join(yaml_lines) + "\n", encoding="utf-8"
    )

    print(f"\nEnglish mainspace: {len(english):,} of {len(mainspace):,}")
    print(f"English infobox:   {len(english_infobox):,} of {len(infobox_titles):,}")
    print(f"distinct prototype-type values: {len(types)}")
    print(
        f"untyped infobox pages: {len(untyped)} -> "
        f"leading templates {untyped_templates.most_common(5)}"
    )
    print(f"wrote {out} and data/cache/type_map_block.yaml")


if __name__ == "__main__":
    if "--cached" in sys.argv and CACHE.is_file():
        analyse(json.loads(CACHE.read_text(encoding="utf-8")))
    else:
        analyse(fetch())
